### GET request to example server
POST localhost:8080/company
Content-Type: application/json

{
  "ticker": "KT"
}

###

GET localhost:8080/company?page=0&size=10
Content-Type: application/json

###

GET localhost:8080/company/autocomplete?keyword=
Content-Type: application/json

###

DELETE localhost:8080/company/AAA
Content-Type: application/json

###

GET localhost:8080/finance/dividend/KT Corporation
Content-Type: application/json