### GET request to example server
POST localhost:8080/company
Content-Type: application/json

{
  "ticker": "AAA"
}

###

GET localhost:8080/company?page=0&size=kim
Content-Type: application/json

###

GET localhost:8080/company/autocomplete?keyword=
Content-Type: application/json

###

DELETE localhost:8080/company/AA
Content-Type: application/json

###

GET localhost:8080/finance/dividend/Alcoa Corporation
Content-Type: application/json